# Generated by Django 4.0.2 on 2022-02-14 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Must include country code and DDD.', regex='^[0-9]{12,13}$')]),
        ),
    ]
