# Generated by Django 4.0.2 on 2022-03-05 00:05

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='pictures/%Y/%m/%d'),
        ),
    ]
